/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pharmacy.management.system;

import dao.ConnectionProvider;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author ESCJAVA04202228
 */
public class EmployeeManage extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeManage
     */
    public EmployeeManage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        empName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Designation = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        empType = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        empSex = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        empAccountType = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        empAddress = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        empId = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        empEmail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        empAccount = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        empIfsc = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        empBasicSalary = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        empAllowance = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        empSepcialAllowance = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        empHra = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        empLocal = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        empBasketAllowance = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        empPf = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        empEsi = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        empAditionalIns = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        empGrosssalary = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        empPerdaysalary = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Saveaction = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        empMobile = new javax.swing.JTextField();
        empLastDate = new com.toedter.calendar.JDateChooser();
        empJoinDate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Employees");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 165, -1));

        jLabel2.setText("Employee Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        empName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empNameActionPerformed(evt);
            }
        });
        getContentPane().add(empName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 200, -1));

        jLabel3.setText("Employee ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 70, 20));

        jLabel4.setText("Designation");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        Designation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sales Man", "Accountant", "Team Leader", "Security" }));
        getContentPane().add(Designation, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 200, -1));

        jLabel5.setText("Employee Type");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        empType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Permanent", "Temporary" }));
        getContentPane().add(empType, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 200, -1));

        jLabel6.setText("Sex");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        empSex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Transgender" }));
        getContentPane().add(empSex, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 200, -1));

        jLabel7.setText("Account");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        empAccountType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Salary Account", "Other Account" }));
        getContentPane().add(empAccountType, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 200, -1));

        jLabel8.setText("Address");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, -1, -1));

        empAddress.setColumns(20);
        empAddress.setRows(5);
        jScrollPane1.setViewportView(empAddress);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 220, 80));

        jLabel9.setText("Mob No.");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 50, 20));
        getContentPane().add(empId, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 200, -1));

        jLabel10.setText("Email ID");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 50, 20));
        getContentPane().add(empEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 220, 20));

        jLabel11.setText(" Account No.");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, -1, -1));

        empAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empAccountActionPerformed(evt);
            }
        });
        getContentPane().add(empAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 220, -1));

        jLabel12.setText("IFSC Code");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 60, 20));
        getContentPane().add(empIfsc, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 220, -1));

        jLabel13.setText("Basic Salary");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, -1, -1));

        empBasicSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empBasicSalaryActionPerformed(evt);
            }
        });
        getContentPane().add(empBasicSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 90, 120, -1));

        jLabel14.setText("Allowance");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, 60, 20));
        getContentPane().add(empAllowance, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 130, 120, -1));

        jLabel15.setText("Special Allowance");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, 100, -1));

        empSepcialAllowance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empSepcialAllowanceActionPerformed(evt);
            }
        });
        getContentPane().add(empSepcialAllowance, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 170, 110, -1));

        jLabel16.setText("HRA");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 210, 30, 20));
        getContentPane().add(empHra, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 210, 120, -1));

        jLabel17.setText("Local Conv.");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 260, -1, -1));
        getContentPane().add(empLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 250, 120, -1));

        jLabel18.setText("Basket Allow.");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 290, -1, -1));
        getContentPane().add(empBasketAllowance, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 290, 120, -1));

        jLabel19.setText("PF Deducation");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 130, 80, 20));
        getContentPane().add(empPf, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 130, 110, -1));

        jLabel20.setText("ESI Deducation");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 170, -1, -1));
        getContentPane().add(empEsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 170, 110, -1));

        jLabel21.setText("Aditional Ins.");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 90, -1, -1));
        getContentPane().add(empAditionalIns, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 90, 110, -1));

        jLabel22.setText("Gross Salary");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 210, -1, -1));
        getContentPane().add(empGrosssalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 210, 110, -1));

        jLabel23.setText("Per Day Salary");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 250, -1, -1));
        getContentPane().add(empPerdaysalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 250, 110, -1));

        jLabel24.setText("Emp Join Date");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 290, -1, 20));

        jLabel25.setText("Emp Last Date");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 320, 80, 20));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Employee ID", "Employee Name", "Designation", "Employee Type", "Sex", "Account", "Address", "Mob No.", "Email ID", "Bank Account No.", "IFSC Code", "Basic Salary", "Allowance", "Special Allowance", "HRA", "Local Conv.", "Basket Allow.", "Aditional Ins.", "PF Deducation", "ESI Deducation", "Gross Salary", "Per Day Salary", "Employee Join Date", "Employee Last Date"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 1440, 320));

        Saveaction.setText("Save");
        Saveaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveactionActionPerformed(evt);
            }
        });
        getContentPane().add(Saveaction, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, -1, -1));

        jButton2.setText("Modify");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 710, -1, -1));

        jButton3.setText("Delete");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 710, -1, -1));

        jLabel26.setText("Employee Name");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 710, -1, 20));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 710, 180, -1));

        jButton4.setText("Search");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 710, -1, -1));

        jButton5.setText("PDF");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 710, -1, -1));

        jButton6.setText("EXCEL");
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 710, -1, -1));

        jButton7.setText("PRINT");
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 710, -1, -1));
        getContentPane().add(empMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 220, -1));
        getContentPane().add(empLastDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 320, -1, -1));
        getContentPane().add(empJoinDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 290, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void empAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empAccountActionPerformed

    private void SaveactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveactionActionPerformed
        String employeeName = empName.getText();
        String empId = this.empId.getText();
        String designation = (String) Designation.getSelectedItem();
        String empType = (String) empAccountType.getSelectedItem();
        String empSex = (String) this.empSex.getSelectedItem();
        String Account = (String) empAccountType.getSelectedItem();
        String empAddress = this.empAddress.getText();
        String mobile = empMobile.getText();
        String email = empEmail.getText();
        String accountNo = empAccount.getText();
        String ifsc = empIfsc.getText();
        String basicSalary = empBasicSalary.getText();
        String allowance = empAllowance.getText();
        String specialAllowance = empSepcialAllowance.getText();
        String hra = empHra.getText();
        String localConv = empLocal.getText();
        String basketAllowance = empBasketAllowance.getText();
        String additionalIns = empAditionalIns.getText();
        String pf = empPf.getText();
        String esi = empEsi.getText();
        String grossSalary = empGrosssalary.getText();
        String perDaySalary = empPerdaysalary.getText();

        // Assuming this.empJoinDate returns a Date object
        Date empJoinDate = this.empJoinDate.getDate();
        Date empLastDate = this.empLastDate.getDate();
// Create a SimpleDateFormat to format the date
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

// Format the date as 'yyyy-MM-dd'
        String formattedJoinDate = sdf.format(empJoinDate);
        String formattedLastDate = sdf.format(empLastDate);
        try {
            Connection con = ConnectionProvider.getCon();
            PreparedStatement ps = con.prepareStatement("INSERT INTO Employee (empId, empName, designation, empType, empSex, empAccount, empAddress, mobile, email, accountno, ifsc, basicSalary, allowance, specialAllowance, hra, localConv, basketAllowance, additionalIns, pf, esi, grossSalary, perdaysalary, joindate, lastdate) "
                    + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");

            ps.setString(1, empId);
            ps.setString(2, employeeName);
            ps.setString(3, designation);
            ps.setString(4, empType);
            ps.setString(5, empSex);
            ps.setString(6, Account);
            ps.setString(7, empAddress);
            ps.setString(8, mobile);
            ps.setString(9, email);
            ps.setString(10, accountNo);
            ps.setString(11, ifsc);
            ps.setString(12, basicSalary);
            ps.setString(13, allowance);
            ps.setString(14, specialAllowance);
            ps.setString(15, hra);
            ps.setString(16, localConv);
            ps.setString(17, basketAllowance);
            ps.setString(18, additionalIns);
            ps.setString(19, pf);
            ps.setString(20, esi);
            ps.setString(21, grossSalary);
            ps.setString(22, perDaySalary);
            ps.setString(23, formattedJoinDate);
            ps.setString(24, formattedLastDate);

            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Saved Successfully");
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_SaveactionActionPerformed

    private void empNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empNameActionPerformed

    private void empSepcialAllowanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empSepcialAllowanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empSepcialAllowanceActionPerformed

    private void empBasicSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empBasicSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empBasicSalaryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeManage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Designation;
    private javax.swing.JButton Saveaction;
    private javax.swing.JTextField empAccount;
    private javax.swing.JComboBox<String> empAccountType;
    private javax.swing.JTextArea empAddress;
    private javax.swing.JTextField empAditionalIns;
    private javax.swing.JTextField empAllowance;
    private javax.swing.JTextField empBasicSalary;
    private javax.swing.JTextField empBasketAllowance;
    private javax.swing.JTextField empEmail;
    private javax.swing.JTextField empEsi;
    private javax.swing.JTextField empGrosssalary;
    private javax.swing.JTextField empHra;
    private javax.swing.JTextField empId;
    private javax.swing.JTextField empIfsc;
    private com.toedter.calendar.JDateChooser empJoinDate;
    private com.toedter.calendar.JDateChooser empLastDate;
    private javax.swing.JTextField empLocal;
    private javax.swing.JTextField empMobile;
    private javax.swing.JTextField empName;
    private javax.swing.JTextField empPerdaysalary;
    private javax.swing.JTextField empPf;
    private javax.swing.JTextField empSepcialAllowance;
    private javax.swing.JComboBox<String> empSex;
    private javax.swing.JComboBox<String> empType;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
